In [1]:
import torch.nn as nn
import torch

input = torch.randn(10,4096)

linear = nn.Linear(in_features=4096, out_features=10)
linear(input).shape



torch.Size([10, 10])

In [2]:

print(linear.weight.shape)
linear.weight

torch.Size([10, 4096])


Parameter containing:
tensor([[-1.1364e-02,  1.5212e-03,  1.3277e-02,  ..., -3.8672e-03,
         -1.0029e-02, -7.1631e-03],
        [ 1.4980e-02, -8.3938e-03,  1.1787e-02,  ...,  9.3822e-03,
         -4.2286e-03, -1.8047e-03],
        [ 9.8638e-03,  6.8385e-03, -4.2143e-04,  ..., -1.7639e-06,
         -6.6750e-03,  1.2456e-02],
        ...,
        [ 1.2177e-02, -6.7710e-04, -9.9451e-03,  ..., -2.0006e-03,
         -6.0402e-03,  3.3831e-03],
        [ 3.8164e-03, -4.5605e-03, -1.0786e-02,  ..., -1.1338e-03,
          2.1666e-03, -1.4094e-02],
        [ 1.3870e-02,  1.0456e-02,  1.3751e-02,  ...,  1.1077e-02,
          1.4328e-02, -7.3788e-03]], requires_grad=True)

In [3]:
linear.bias

Parameter containing:
tensor([ 0.0156, -0.0083,  0.0142, -0.0121,  0.0123,  0.0044, -0.0112, -0.0138,
        -0.0146, -0.0114], requires_grad=True)

In [5]:
input.dtype

torch.float32

In [6]:
torch.min(input)

tensor(-4.3487)

In [7]:
torch.max(input)

tensor(3.9431)

In [8]:
torch.argmax(input)

tensor(17218)

In [9]:
torch.sum(input)

tensor(13.7541)

In [12]:
t1 = torch.transpose(input, 0, 1)

In [13]:
t2 = input

In [15]:
id(t1) == id(t2)

False

In [17]:
torch.is_tensor(t1)

True

In [18]:
torch.is_tensor(t2)

True

In [20]:
v1 = input.view(4096,10)

In [21]:
v1

tensor([[-2.1540,  2.0841, -0.6671,  ...,  1.0038,  1.6273, -1.1669],
        [ 0.9275, -0.7299, -0.4993,  ...,  1.3026,  0.2139,  1.1118],
        [-0.2285,  1.0570, -0.2162,  ...,  0.3213,  1.4926,  0.3952],
        ...,
        [ 1.0647, -0.6663, -0.4645,  ..., -0.0628, -1.8040, -0.5422],
        [-1.3157, -0.4761,  0.0895,  ..., -0.0379,  0.8445,  1.1400],
        [ 1.2183,  0.3849, -0.5355,  ..., -0.6890, -0.5789, -0.6009]])