In [15]:
import torch

# 创建一个随机张量来模拟我们的图像数据
images = torch.randn(1, 3, 4, 4)
print("Original shape:", images.shape)

Original shape: torch.Size([1, 3, 4, 4])


In [16]:
images

tensor([[[[-1.0378,  0.3451, -1.0325, -0.0298],
          [ 0.6454,  1.7000, -1.2739,  0.6769],
          [ 0.8280,  0.1270,  0.2186,  1.1609],
          [ 0.0413,  0.5314, -0.2105,  2.3176]],

         [[ 0.7657, -0.4426,  0.1933, -0.1650],
          [-0.4425,  0.9623,  0.1812, -1.6412],
          [ 0.2697,  0.3427, -0.4270,  0.7763],
          [-0.2115, -0.4130, -0.0480, -0.7017]],

         [[ 0.7782, -0.1634, -0.4567, -0.9424],
          [-1.1609,  1.0877,  0.6216,  0.3707],
          [-0.3905,  0.6509,  1.4288, -1.2158],
          [ 0.7221,  1.3479,  0.0556,  0.3918]]]])

In [17]:
images_t1 = images.transpose(1, 2)
print("Transposed shape:", images_t1.shape)
images_t1

Transposed shape: torch.Size([1, 4, 3, 4])


tensor([[[[-1.0378,  0.3451, -1.0325, -0.0298],
          [ 0.7657, -0.4426,  0.1933, -0.1650],
          [ 0.7782, -0.1634, -0.4567, -0.9424]],

         [[ 0.6454,  1.7000, -1.2739,  0.6769],
          [-0.4425,  0.9623,  0.1812, -1.6412],
          [-1.1609,  1.0877,  0.6216,  0.3707]],

         [[ 0.8280,  0.1270,  0.2186,  1.1609],
          [ 0.2697,  0.3427, -0.4270,  0.7763],
          [-0.3905,  0.6509,  1.4288, -1.2158]],

         [[ 0.0413,  0.5314, -0.2105,  2.3176],
          [-0.2115, -0.4130, -0.0480, -0.7017],
          [ 0.7221,  1.3479,  0.0556,  0.3918]]]])

In [18]:
images_t2 = images.transpose(1, 3)

In [19]:
print("Transposed shape:", images_t2.shape)

Transposed shape: torch.Size([1, 4, 4, 3])


In [20]:
images_t2

tensor([[[[-1.0378,  0.7657,  0.7782],
          [ 0.6454, -0.4425, -1.1609],
          [ 0.8280,  0.2697, -0.3905],
          [ 0.0413, -0.2115,  0.7221]],

         [[ 0.3451, -0.4426, -0.1634],
          [ 1.7000,  0.9623,  1.0877],
          [ 0.1270,  0.3427,  0.6509],
          [ 0.5314, -0.4130,  1.3479]],

         [[-1.0325,  0.1933, -0.4567],
          [-1.2739,  0.1812,  0.6216],
          [ 0.2186, -0.4270,  1.4288],
          [-0.2105, -0.0480,  0.0556]],

         [[-0.0298, -0.1650, -0.9424],
          [ 0.6769, -1.6412,  0.3707],
          [ 1.1609,  0.7763, -1.2158],
          [ 2.3176, -0.7017,  0.3918]]]])

In [23]:
id(images)

125454924686544

In [24]:
id(images_t2)

125454924691504